name: github-cloner-ci

on:
  push:
    branches:
      - main
      - develop
      - feat/**
      - chore/**
      - fix/**
  pull_request:
    branches:
      - main
      - develop
      - feat/**
      - chore/**
      - fix/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: run linting
      run: |
        flake8 github-cloner.py
        pylint github-cloner.py

    - name: run type checking
      run: python3 -m mypy github-cloner.py

    - name: run unit tests
      run: python3 -m pytest tests/ -v

    - name: validate script functionality
      run: python3 github-cloner.py --help